### ISSUE TITLE
cannot use intermediate position and tilt/ventilaton

### ISSUE THREAD

**Issue by andy-st** [W00D00/home-assistant-elero#10]
Accoding to the Elero Stick documentation, there are 5 commands:

![image](https://user-images.githubusercontent.com/57436486/68615335-2559d700-04c3-11ea-822b-1a95a18ff5c0.png)

I've defined a shutter like this:

```
    - platform: elero
      covers:
          rolloarbeitszimmer:
              serial_number: A503EN6C
              name: Arbeitszimmer
              channel: 1
              device_class: roller shutter
              supported_features:
                  - up
                  - down
                  - stop
                  - set_position
                  - set_tilt_position
```

It looks like this:

![image](https://user-images.githubusercontent.com/57436486/68615493-7b2e7f00-04c3-11ea-9926-ff67c92ef2fd.png)

But if I use the sliders for position or tilt, just nothing happens.

I can then find in the log file:
2019-11-11 19:39:55 WARNING (SyncWorker_14) [custom_components.elero.cover] Elero - transmitter: 'A503EN6C' ch: '1' The set cover tilt position function is not implemented yet.

So directly I can only click on “open”, “stop” and “close”.
I would expect that there is also something to click on “move to intermediate position” and “move to ventilation position”. Both commands should work without giving an argument to this method. I mean, the Elero shutters only can execute e.g. “move to ventilation position”, but they do not support something like “move 30%”. The both positions “intermediate” and “ventilation” can be programmed separately and are stored in the shutter itself.

It would be great if there would a way how you could send the shutters to the predefined "intermediate position" and "tilt/ventilation". :-)

**Comment by W00D00** [comment]
Hi @andy-st,

The intermediate and ventilation functions are working well for me. 
Based on your configuration, you have to add the 'open_tilt' and the 'close_tilt' functions to your config. The 'set_position' and the 'set_tilt_position' features alone are not enough. However, in the latest version of the Elero lib on the Github these two slider functions are not implemented. Please give me some time and I will implement a solution to the sliders.

Cover 'Position' and 'Tilt position' Sliders

Unfortunately, by default, the Position slider is not configurable on a cover so, the 'step' of the slider either. Thus, the 'set_position' and the 'set_tilt_position' functions are not usable. Another problem that the Elero devices are not supporting these functions.

For the Elero 'intermediate' function use the 'open_tilt' HA function and the Elero 'ventilation' function use the 'close_tilt' HA function.

Nevertheless, these controls are shown and useable only if the pop-up window of the given cover is open.

Alternative methods for the Elero 'intermediate' and the 'ventilation' functions:

1. [Call a Service](https://www.home-assistant.io/docs/scripts/service-calls/)


entities:
  - name: Intermediate
    service: cover.close_cover_tilt
    service_data:
      entity_id: cover.all_cover_group
    type: call-service
  - name: Ventilation
    service: cover.open_cover_tilt
    service_data:
      entity_id: cover.all_cover_group
    type: call-service


2. An ['input_number'](https://www.home-assistant.io/integrations/input_number/) slider with automation.

input_number:
    diningroom_set_position:
        name: Position
        mode: slider
        initial: 0
        min: 0
        max: 100
        step: 25

automation:
  - alias: diningroom_set_position
    trigger:
        platform: numeric_state
        entity_id: input_number.diningroom_set_position
        to: 25
    action:
        - service: cover.close_cover_tilt
          entity_id:
            - cover.diningroom


3. An ['input_select'](https://www.home-assistant.io/integrations/input_select/) Scene with automation.

input_select:
    scene_diningroom:
        name: Scene
        options:
            - open
            - close
            - stop
            - intermediate
            - ventilation

automation:
  - alias: Diningroom scene
    trigger:
      platform: state
      entity_id: input_select.scene_diningroom
      to: intermediate
    action:
        - service: cover.close_cover_tilt
          entity_id:
            - cover.diningroom

I hope these will help you until I will deploy a new version of the Elero lib with new slider support.

Thanks

**Comment by andy-st** [comment]
Hello @W00D00,

wow, thank you so much for your detailled description! 👍 

I've now added all functions like this:

```
    - platform: elero
      covers:
          rolloarbeitszimmer:
              serial_number: A503EN6C
              name: Arbeitszimmer
              channel: 1
              device_class: roller shutter
              supported_features:
                  - up
                  - down
                  - stop
                  - set_position
                  - open_tilt
                  - close_tilt
                  - stop_tilt
                  - set_tilt_position
```

> For the Elero 'intermediate' function use the 'open_tilt' HA function and the Elero 'ventilation' function use the 'close_tilt' HA function. 
Nevertheless, these controls are shown and useable only if the pop-up window of the given cover is open.

So I understood that I should use
- intermediate --> open_tilt
- ventilation --> close_tilt

For me, it is still not working. :-( Here comes an example:

The shutter is opened and I open the pop-up window:

![image](https://user-images.githubusercontent.com/57436486/69239776-48f3e000-0b9b-11ea-9d7c-1d0121524de4.png)

As you can see I can click only on "Close Tilt" ( = ventilation), but not on "Open Tilt" ( = intermediate)?
Anyways, when I click on "Close Tilt" the shutter is moving to the intemediate (!) position, but I still cannot click "Open Tilt":

![image](https://user-images.githubusercontent.com/57436486/69239986-c881af00-0b9b-11ea-96eb-5c3cdcafcfc0.png)

So to summarize:
- "Close Tilt" moves to intermediate position and not to the ventilation position. 
- "Open Tilt" I can never click, it is always grey-out in the pop-up window.

I am using also a simple Elero UniTec-868 remote control and this is working fine:
- 2x clicks on "Open / Up" then the shutter moves to ventialation
- 2x clicks on "Close / Down" then the shutter moves to the intermediate position

Do you have idea what could be wrong?
Is my understanding correct, that it should work with the two arrows in the pop-up window before I start working with the services / input number / input select / ...?

Thanks a ton again!
