### ISSUE TITLE
set_position does not work for my roller shutter

### ISSUE THREAD

**Issue by chrfritsch** [W00D00/home-assistant-elero#3]
From the documentation, I assume that setting a specific position should work.

When I call set_cover_position on one of my roller shutters I get:

Elero transmitter: '1' ch: '{2}'         The set cover position function is not implemented yet.

My config is:

```
elero:
  transmitters:
  - transmitter_id: 1
    port: '/dev/ttyUSB0'

cover:
  - platform: elero
    covers:
      livingroom_tv:
        name: rollershutter_livingroom_tv
        device_class: roller shutter
        transmitter_id: 1
        channel: 2
        supported_features:
        - up
        - down
        - stop
        - set_position
```

I am having a Elero RolTop M10-868.

Did I something wrong?
