### ISSUE TITLE
cannot send commands to groups if the members having different states

### ISSUE THREAD

**Issue by andy-st** [W00D00/home-assistant-elero#9]
I have the issue that I cannot send commands to a group of shutters, if some of the group members have a different state. For example:

![image](https://user-images.githubusercontent.com/57436486/68615144-c7c58a80-04c2-11ea-812a-56e79c49883b.png)

**Comment by W00D00** [comment]
Hi @andy-st,

As I remember it is not the first time when someone complains the status of the groups. Unfortunately, I am not able to reproduce this issue in my system. I can control my groups and the covers in them without any problem. The group status represents the right status of the covers in the given group. May be important, that I have the latest HA and lates Elero lib from the Github. Please verify your system that is the latest because, based on your log, you are running not the latest Elero lib. 

I think this problem has not relation to the Elero lib just the HA core.

Please describe how did you create the group.

Thanks

**Comment by andy-st** [comment]
Thank you for you feedback @W00D00.
You are right, I have not used the latest Elero lib (it was around 1 week older), but I've now updated it.

Even after a reboot of HA the behaviour is still the same. 
Also I have the new latest HA version 0.101.3.

![image](https://user-images.githubusercontent.com/57436486/69236829-ae909e00-0b94-11ea-9bf1-e35198cd3606.png)

My configuration is quite simple (just a snipped for the one example):

```
elero:
  transmitters:
    - serial_number: A503EN6C
```
```
cover:
    - platform: elero
      covers:
          rolloschlafzimmerrechts:
              serial_number: A503EN6C
              name: SchlafzimmerRechts
              channel: 3
              device_class: roller shutter
              supported_features:
                  - up
                  - down
                  - stop
          rolloschlafzimmermitte:
              serial_number: A503EN6C
              name: SchlafzimmerMitte
              channel: 4
              device_class: roller shutter
              supported_features:
                  - up
                  - down
                  - stop
          rolloschlafzimmerlinks:
              serial_number: A503EN6C
              name: SchlafzimmerLinks
              channel: 5
              device_class: roller shutter
              supported_features:
                  - up
                  - down
                  - stop
```
                
```
    - platform: group
      name: "Schlafzimmer"
      entities:
          - cover.schlafzimmerrechts
          - cover.schlafzimmermitte
          - cover.schlafzimmerlinks

```

Thank you again for spending so much effort into this lib!
